#!/usr/bin/env python
'''
Program to read or write Extended Display Identification Data (EDID) to
a digital display. Default action is to READ binary EDID data from
specified i2c_device and write it to standard output. With "-w", will
instead read EDID binary data from standard input and WRITE it to
specified i2c_device. Always validates the EDID checksum before allowing
a write to device.
'''
# (C) Mark Blakeney, April 2012.

import os, sys, array, argparse, subprocess, time
from smbus import SMBus

EDID_HDR = 20
EDID_LEN = (128, 256)
EDID_ADDR = 0x50

class stddev(object):
    'Standard input/output device for testing'
    def __init__(self, args):
        'Create standard input/output device'
        pass

    def read(self, n):
        'Read a byte from stdin'
        return array.array('B', os.read(sys.stdin.fileno(), 1)).tolist()[0]

    def write(self, n, val):
        'Write a byte to stdout'
        os.write(sys.stdout.fileno(), array.array('B', (val,)).tostring())

class smbdev(object):
    'SMB device'
    def __init__(self, args):
        'Create SMB device'
        # Need ic2 device module installed
        if subprocess.call(('modprobe', 'i2c-dev')) != 0:
            sys.exit('ERROR: Can not load i2c-dev. Must use sudo or be root.')

        # Access i2c device
        self.smb = SMBus(args.i2c_device_num[0])

    def read(self, n):
        'Read a byte from given SMB device'
        return self.smb.read_byte_data(EDID_ADDR, n)

    def write(self, n, val):
        'Write a byte to given SMB device'
        self.smb.write_byte_data(EDID_ADDR, n, val)

def getlen(edidhdr):
    'Return the number of bytes expected for this edid hdr'
    if edidhdr[18] <= 0 or edidhdr[18] > len(EDID_LEN):
        sys.exit('ERROR: Unknown EDID version %d' % edidhdr[18])

    return EDID_LEN[edidhdr[18] - 1]

def blkname(blk):
    'Return a name for given block number'
    return 'EDID' if blk == 0 else ('Ext block %d' % blk)

def checksum(edid):
    'Return EDID checksum of the given buffer'
    return (0 - (sum(edid[:-1]) % 256)) % 256

def main():
    'Main code'

    # Process command line options
    opt = argparse.ArgumentParser(description=__doc__.strip(),
            formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    opt.add_argument('-w', '--write', action='store_true',
            help='Write EDID to i2c_device from data read from stdin')
    opt.add_argument('-t', '--std', action='store_true',
            help='Read stdin or write stdout only, for testing')
    opt.add_argument('-f', '--fix', action='store_true',
            help='Fix last checksum byte automatically when writing the '
            'EDID and extensions')
    opt.add_argument('-s', '--sleep', default=0.01, type=float,
            help='Sleep this many seconds between writes')
    opt.add_argument('i2c_device_num', nargs=1, type=int,
            help='i2c device number, e.g. 0 or 1 or 2 ..')
    args = opt.parse_args()

    # Assign smb device, or stdin/stdout for testing
    dev = stddev(args) if args.std else smbdev(args)

    if args.write:
        # Read EDID from stdin
        edid = array.array('B', os.read(sys.stdin.fileno(),
            max(EDID_LEN))).tolist()
        edid_len = getlen(edid)
        edid_n = edid[edid_len - 2]
        nbytes = edid_len + (edid_len * edid_n)
        if len(edid) != nbytes:
            sys.exit('ERROR: Input must be %d bytes' % nbytes)

        # Check each EDID block checksum is valid
        for b in range(edid_n + 1):
            x = (b + 1) * edid_len
            actsum = edid[x - 1]
            calsum = checksum(edid[x - edid_len:x])
            if actsum != calsum:
                if args.fix:
                    edid[x - 1] = calsum
                    sys.exit('%s checksum 0x%02x was BAD, rewrote it to '
                            '0x%02x.' % (blkname(b), actsum, calsum))
                else:
                    sys.exit('ERROR: %s checksum 0x%02x is BAD, should be '
                            '0x%02x.' % (blkname(b), actsum, calsum))

        # Write EDID to device
        for i, val in enumerate(edid):
            dev.write(i, val)
            time.sleep(args.sleep)
    else:
        # Read EDID from device
        edid = [dev.read(i) for i in range(EDID_HDR)]
        edid_len = getlen(edid)
        edid += [dev.read(i) for i in range(EDID_HDR, edid_len)]

        # Read extensions from device (if any)
        edid += [dev.read(i) for i in
                range(edid_len, edid_len + edid_len * edid[-2])]

        # Write EDID to stdout
        os.write(sys.stdout.fileno(), array.array('B', edid).tostring())

if __name__ == '__main__':
    main()
